:rocket: adding deploy on heroku

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -120,12 +120,20 @@ jobs:
       - image: circleci/node:dubnium-browsers
     working_directory: ~/deploy
     steps:
-      # why rebuild something we already tested, rebuilding invalidates any previous confidence?!
-      - attach_workspace:
-          at: /tmp
+      - checkout
       - run:
-          name: TODO
-          command: echo "TODO"
+          name: Deploy Master to Heroku
+          command: |
+            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
+      - run:
+          name: Smoke Test
+          command: |
+            # Heroku deploy command will pass even if application crashes. Simple smoke test to make sure app is up.
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/`
+            if [ "$HTTPCODE" -ne 200 ];then
+              echo "heroku app not responding, failing deploy"
+              exit 1
+            fi
 
 workflows:
   version: 2
